export type TriviaQuestion = {
  id: string;
  question: string;
  options: [string, string, string, string];
  answer: "A" | "B" | "C" | "D";
  explanation: string;
};

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  {
    id: "q01",
    question: "Who holds the MLB record for most career home runs?",
    options: ["Hank Aaron", "Barry Bonds", "Babe Ruth", "Alex Rodriguez"],
    answer: "B",
    explanation: "Barry Bonds hit 762 career home runs, surpassing Hank Aaron's record of 755.",
  },
  {
    id: "q02",
    question: "What year was the first modern World Series played?",
    options: ["1898", "1900", "1903", "1910"],
    answer: "C",
    explanation: "The first modern World Series was played in 1903 between the Boston Americans and Pittsburgh Pirates.",
  },
  {
    id: "q03",
    question: "How many stitches are on a regulation MLB baseball?",
    options: ["88", "96", "108", "120"],
    answer: "C",
    explanation: "A regulation MLB baseball has exactly 108 double stitches (216 individual stitches).",
  },
  {
    id: "q04",
    question: "Joe DiMaggio's consecutive-game hitting streak in 1941 stands at how many games?",
    options: ["44", "48", "52", "56"],
    answer: "D",
    explanation: "Joe DiMaggio hit safely in 56 consecutive games in 1941 — a record that still stands today.",
  },
  {
    id: "q05",
    question: "What is the distance from home plate to the pitcher's mound in MLB?",
    options: ["58.5 feet", "60.5 feet", "62 feet", "64 feet"],
    answer: "B",
    explanation: "The pitcher's mound is 60 feet 6 inches (60.5 ft) from home plate.",
  },
  {
    id: "q06",
    question: "Which franchise has won the most World Series championships?",
    options: ["Boston Red Sox", "St. Louis Cardinals", "Los Angeles Dodgers", "New York Yankees"],
    answer: "D",
    explanation: "The New York Yankees have won 27 World Series titles, far more than any other team.",
  },
  {
    id: "q07",
    question: "What is a 'golden sombrero' in baseball?",
    options: [
      "Hitting a walk-off home run",
      "Striking out four times in one game",
      "Hitting for the cycle",
      "A no-hitter through 6 innings",
    ],
    answer: "B",
    explanation: "A golden sombrero is when a batter strikes out four times in a single game.",
  },
  {
    id: "q08",
    question: "Who is known as 'The Say Hey Kid'?",
    options: ["Mickey Mantle", "Duke Snider", "Stan Musial", "Willie Mays"],
    answer: "D",
    explanation: "Willie Mays earned the nickname 'The Say Hey Kid' early in his career with the New York Giants.",
  },
  {
    id: "q09",
    question: "What does ERA stand for?",
    options: [
      "Extra Run Average",
      "Error Run Analysis",
      "Earned Run Average",
      "Extra Runs Allowed",
    ],
    answer: "C",
    explanation: "ERA stands for Earned Run Average — the average number of earned runs a pitcher allows per 9 innings.",
  },
  {
    id: "q10",
    question: "Who broke Major League Baseball's color barrier in 1947?",
    options: ["Satchel Paige", "Larry Doby", "Josh Gibson", "Jackie Robinson"],
    answer: "D",
    explanation: "Jackie Robinson broke MLB's color barrier on April 15, 1947, when he took the field for the Brooklyn Dodgers.",
  },
  {
    id: "q11",
    question: "What does WHIP stand for in baseball statistics?",
    options: [
      "Walks and Hits per Inning Pitched",
      "Walks, Hits, and Innings Pitched",
      "Wild pitches, Hits, Innings Pitched",
      "Weighted Hits In Pitching",
    ],
    answer: "A",
    explanation: "WHIP stands for Walks and Hits per Inning Pitched — a measure of how many base runners a pitcher allows per inning.",
  },
  {
    id: "q12",
    question: "Who holds the MLB record for most career stolen bases?",
    options: ["Lou Brock", "Tim Raines", "Vince Coleman", "Rickey Henderson"],
    answer: "D",
    explanation: "Rickey Henderson stole 1,406 bases in his career, nearly 500 more than second-place Lou Brock.",
  },
  {
    id: "q13",
    question: "What is an 'infield fly' in baseball?",
    options: [
      "Any fly ball hit to the infield",
      "A balk by the pitcher",
      "An automatic out on a pop-up with runners on 1st and 2nd (or bases loaded) and less than 2 outs",
      "A foul tip caught by the catcher",
    ],
    answer: "C",
    explanation: "The infield fly rule calls the batter automatically out to prevent fielders from intentionally dropping pop-ups to get easy double plays.",
  },
  {
    id: "q14",
    question: "What does OBP stand for?",
    options: [
      "Official Batter Points",
      "On-Base Percentage",
      "Out-Ball Percentage",
      "Overall Batting Performance",
    ],
    answer: "B",
    explanation: "OBP (On-Base Percentage) measures how often a batter reaches base via hit, walk, or hit-by-pitch.",
  },
  {
    id: "q15",
    question: "Nolan Ryan set the single-season strikeout record in 1973 with how many Ks?",
    options: ["348", "363", "383", "401"],
    answer: "C",
    explanation: "Nolan Ryan struck out 383 batters in 1973 with the California Angels, a record that still stands.",
  },
  {
    id: "q16",
    question: "What is a 'squeeze play'?",
    options: [
      "A pickoff attempt at first base",
      "A double steal with runners on 1st and 2nd",
      "A bunt designed to score a runner from third base",
      "A hit-and-run with a runner on second",
    ],
    answer: "C",
    explanation: "A squeeze play is when a batter bunts with a runner on third base, trying to score the runner on the play.",
  },
  {
    id: "q17",
    question: "What is 'painting the corner' in baseball?",
    options: [
      "A hit down the foul line",
      "A pitch that barely catches the edge of the strike zone",
      "A stolen base on a pitch in the dirt",
      "A slide into home plate",
    ],
    answer: "B",
    explanation: "Painting the corner means throwing a pitch that catches the very edge of the strike zone — a tough pitch for hitters to hit and umpires to call.",
  },
  {
    id: "q18",
    question: "In what year did the designated hitter rule first appear in the American League?",
    options: ["1968", "1971", "1973", "1976"],
    answer: "C",
    explanation: "The American League adopted the DH rule in 1973. The NL followed in 2022 when MLB made it universal.",
  },
  {
    id: "q19",
    question: "What does 'going yard' mean in baseball slang?",
    options: ["Stealing home plate", "Hitting a triple", "Hitting a home run", "An inside-the-park home run only"],
    answer: "C",
    explanation: "'Going yard' means hitting a home run — the ball leaves the park (the yard).",
  },
  {
    id: "q20",
    question: "A pitcher who records 27 consecutive outs without allowing a baserunner has thrown a…",
    options: ["One-hitter", "Perfect game", "No-hitter", "Complete game shutout"],
    answer: "B",
    explanation: "A perfect game requires retiring all 27 batters in order — no hits, no walks, no errors, no runners of any kind.",
  },
  {
    id: "q21",
    question: "What is a 'rundown' in baseball?",
    options: [
      "A play where the fielding team runs down a fly ball",
      "A play where a baserunner is caught between two bases and fielders tag them out",
      "A sprint time drill in practice",
      "When a pitcher's velocity drops late in the game",
    ],
    answer: "B",
    explanation: "A rundown (also called a 'pickle') is when a baserunner is caught between two bases and fielders throw back and forth trying to tag them out.",
  },
  {
    id: "q22",
    question: "How many balls does it take to walk a batter?",
    options: ["3", "4", "5", "It depends on the count"],
    answer: "B",
    explanation: "Four balls result in a walk (also called a base on balls), allowing the batter to advance to first base.",
  },
  {
    id: "q23",
    question: "Cal Ripken Jr. is famous for playing in how many consecutive games?",
    options: ["1,897", "2,130", "2,632", "2,900"],
    answer: "C",
    explanation: "Cal Ripken Jr. played in 2,632 consecutive games from 1982 to 1998, breaking Lou Gehrig's record of 2,130.",
  },
  {
    id: "q24",
    question: "What pitch typically moves away from a right-handed batter when thrown by a right-handed pitcher?",
    options: ["Two-seam fastball", "Curveball", "Changeup", "Slider"],
    answer: "D",
    explanation: "A slider thrown by a right-handed pitcher typically breaks down and away from a right-handed batter.",
  },
  {
    id: "q25",
    question: "What does it mean to 'hit for the cycle'?",
    options: [
      "Hit a home run in four consecutive at-bats",
      "Hit a single, double, triple, and home run in the same game",
      "Go 4-for-4 in a game",
      "Hit a leadoff home run four games in a row",
    ],
    answer: "B",
    explanation: "Hitting for the cycle means a batter gets a single, double, triple, and home run all in the same game — a rare feat.",
  },
  {
    id: "q26",
    question: "What is the standard height of a pitcher's mound in MLB?",
    options: ["8 inches", "10 inches", "12 inches", "15 inches"],
    answer: "B",
    explanation: "The pitcher's mound is 10 inches above the level of home plate. It was lowered from 15 inches after the 1968 'Year of the Pitcher.'",
  },
  {
    id: "q27",
    question: "Which player is nicknamed 'The Kid' and won the 1997 World Series MVP?",
    options: ["Ken Griffey Jr.", "Liván Hernández", "Derek Jeter", "Gary Sheffield"],
    answer: "B",
    explanation: "Liván Hernández won the 1997 World Series MVP with the Florida Marlins. Ken Griffey Jr. is 'The Kid' but never won a World Series.",
  },
  {
    id: "q28",
    question: "What is a 'can of corn' in baseball?",
    options: [
      "A slow roller to the infield",
      "An easy, routine fly ball to an outfielder",
      "A pitch tipped off the catcher's glove",
      "A double play ball",
    ],
    answer: "B",
    explanation: "A 'can of corn' is an easy fly ball to an outfielder — the term dates back to old grocery stores where clerks used a pole to knock canned goods off high shelves into their aprons.",
  },
  {
    id: "q29",
    question: "How many innings are in a regulation MLB game?",
    options: ["7", "8", "9", "It depends on the score"],
    answer: "C",
    explanation: "A regulation MLB game is 9 innings. A game can end earlier if it's official (5+ innings) and weather or other conditions prevent completion.",
  },
  {
    id: "q30",
    question: "Who won the most Cy Young Awards in MLB history?",
    options: ["Roger Clemens", "Randy Johnson", "Greg Maddux", "Clayton Kershaw"],
    answer: "A",
    explanation: "Roger Clemens won 7 Cy Young Awards — more than any other pitcher in history.",
  },
  {
    id: "q31",
    question: "What does 'OPS' stand for in batting statistics?",
    options: [
      "On-base Plus Slugging",
      "Overall Player Score",
      "Official Plate Statistics",
      "On-base Percentage Score",
    ],
    answer: "A",
    explanation: "OPS (On-base Plus Slugging) adds a player's on-base percentage and slugging percentage together and is a quick measure of offensive value.",
  },
  {
    id: "q32",
    question: "What is a 'walk-off' in baseball?",
    options: [
      "When a pitcher is pulled from the game",
      "When a batter takes four balls for a walk",
      "A hit or play that ends the game in the home team's favor in the last inning",
      "When a player is ejected and walks off the field",
    ],
    answer: "C",
    explanation: "A walk-off is any play that ends the game with the home team winning — the fielding team literally has to walk off the field.",
  },
  {
    id: "q33",
    question: "Which pitcher holds the MLB record for most career strikeouts?",
    options: ["Randy Johnson", "Roger Clemens", "Steve Carlton", "Nolan Ryan"],
    answer: "D",
    explanation: "Nolan Ryan struck out 5,714 batters in his career — over 800 more than second-place Randy Johnson (4,875).",
  },
  {
    id: "q34",
    question: "What is a 'rubber game' in baseball?",
    options: [
      "A game played on artificial turf",
      "The deciding third game of a three-game series",
      "An extra-innings game",
      "A rainout makeup game",
    ],
    answer: "B",
    explanation: "A rubber game is the deciding game of a series when each team has won an equal number of games — the team that wins 'breaks the rubber.'",
  },
  {
    id: "q35",
    question: "Ted Williams hit .406 in 1941. What does this mean?",
    options: [
      "He had 406 total hits",
      "He reached base 40.6% of the time",
      "He got a hit in 40.6% of his at-bats",
      "He had an OPS of .406",
    ],
    answer: "C",
    explanation: "A batting average of .406 means Williams got a hit in 40.6% of his official at-bats. No player has batted .400 or higher since.",
  },
  {
    id: "q36",
    question: "What is the 'hot corner' in baseball?",
    options: ["Home plate", "Third base", "The pitcher's mound", "First base"],
    answer: "B",
    explanation: "Third base is called the 'hot corner' because batters often pull hard line drives toward third basemen, requiring quick reflexes.",
  },
  {
    id: "q37",
    question: "Which team did Babe Ruth play for before the New York Yankees?",
    options: ["New York Giants", "Philadelphia Athletics", "Boston Red Sox", "Detroit Tigers"],
    answer: "C",
    explanation: "Babe Ruth started his career with the Boston Red Sox and was sold to the Yankees after the 1919 season — a trade that became known as the 'Curse of the Bambino.'",
  },
  {
    id: "q38",
    question: "What does 'BB' stand for on a baseball scorecard?",
    options: ["Bunt Balk", "Base on Balls", "Batter's Box", "Batted Ball"],
    answer: "B",
    explanation: "BB stands for Base on Balls — the official term for a walk, when a batter receives four balls and advances to first base.",
  },
  {
    id: "q39",
    question: "What is a 'sacrifice fly'?",
    options: [
      "A bunt that advances a runner",
      "A fly ball caught for an out that scores a runner from third",
      "A pop-up the catcher drops intentionally",
      "A fly ball that lands in foul territory",
    ],
    answer: "B",
    explanation: "A sacrifice fly is a fly ball caught for an out that allows a runner on third to tag up and score. It does not count against the batter's average.",
  },
  {
    id: "q40",
    question: "What year was the MLB draft introduced?",
    options: ["1955", "1960", "1965", "1970"],
    answer: "C",
    explanation: "The MLB First-Year Player Draft was introduced in 1965 to give weaker teams priority access to amateur talent.",
  },
  {
    id: "q41",
    question: "What is the distance between each base on a standard baseball diamond?",
    options: ["80 feet", "90 feet", "100 feet", "110 feet"],
    answer: "B",
    explanation: "The bases are 90 feet apart on a standard baseball diamond — a distance that creates extremely close plays at first base.",
  },
  {
    id: "q42",
    question: "Mike Trout won his first MVP award with which team?",
    options: ["Anaheim Angels", "Los Angeles Angels", "California Angels", "Texas Rangers"],
    answer: "B",
    explanation: "Mike Trout won the 2014 AL MVP (his first unanimous MVP) with the Los Angeles Angels of Anaheim.",
  },
  {
    id: "q43",
    question: "What is a 'utility player' in baseball?",
    options: [
      "A player who handles the team's equipment",
      "A backup catcher",
      "A player who can play multiple positions",
      "A player who only pinch-hits",
    ],
    answer: "C",
    explanation: "A utility player is versatile enough to play multiple positions, giving the manager flexibility with lineups and substitutions.",
  },
  {
    id: "q44",
    question: "Which stat measures the total bases a batter accumulates per at-bat?",
    options: ["Batting Average", "On-Base Percentage", "Slugging Percentage", "wRC+"],
    answer: "C",
    explanation: "Slugging percentage divides total bases (1 for single, 2 for double, 3 for triple, 4 for HR) by at-bats.",
  },
  {
    id: "q45",
    question: "What is a 'balk' in baseball?",
    options: [
      "A pitch that hits the batter",
      "An illegal pitching motion that allows baserunners to advance one base",
      "A pitch that bounces in the dirt",
      "When a fielder drops a throw",
    ],
    answer: "B",
    explanation: "A balk is an illegal motion by the pitcher with runners on base. All runners advance one base as a penalty.",
  },
  {
    id: "q46",
    question: "Mariano Rivera is famous for which pitch?",
    options: ["Knuckleball", "Eephus pitch", "Cut fastball (cutter)", "Split-finger fastball"],
    answer: "C",
    explanation: "Mariano Rivera's cut fastball (cutter) was arguably the most dominant single pitch in baseball history, helping him become the all-time saves leader.",
  },
  {
    id: "q47",
    question: "What does 'BABIP' stand for?",
    options: [
      "Batting Average on Balls In Play",
      "Bases Allowed By Innings Pitched",
      "Batted Average By Infield Position",
      "Batting Average Based on Individual Performance",
    ],
    answer: "A",
    explanation: "BABIP (Batting Average on Balls In Play) measures how often balls put in play fall for hits, excluding home runs and strikeouts. It helps evaluate whether results reflect true skill or luck.",
  },
  {
    id: "q48",
    question: "What is a 'no-doubter' home run?",
    options: [
      "A home run that barely clears the fence",
      "A home run so well-hit there is no doubt it will leave the park",
      "A home run in the 9th inning",
      "A walk-off home run",
    ],
    answer: "B",
    explanation: "A 'no-doubter' is a home run hit so hard and so far that there was never any question it was going out — usually a ball crushed to deep center or the upper deck.",
  },
  {
    id: "q49",
    question: "Who is the only pitcher to throw two no-hitters in the same season in the modern era?",
    options: ["Sandy Koufax", "Nolan Ryan", "Johnny Vander Meer", "Bob Feller"],
    answer: "C",
    explanation: "Johnny Vander Meer threw back-to-back no-hitters in June 1938 — the only pitcher ever to throw two consecutive no-hitters.",
  },
  {
    id: "q50",
    question: "What is the proper way for a fielder to back up a base on a throw?",
    options: [
      "Stand directly behind the base",
      "Stand at an angle behind the base so an overthrow doesn't get past you",
      "Stand in front of the base to cut the ball off",
      "Back up is not necessary if another fielder is covering",
    ],
    answer: "B",
    explanation: "A backup fielder should angle themselves behind the base so an overthrow or wild bounce doesn't get past them and allow extra bases.",
  },
];

export function getRandomQuestion(excludeIds: string[] = []): TriviaQuestion {
  const pool = TRIVIA_QUESTIONS.filter((q) => !excludeIds.includes(q.id));
  const source = pool.length > 0 ? pool : TRIVIA_QUESTIONS;
  return source[Math.floor(Math.random() * source.length)];
}
