export type TriviaQuestion = {
  id: string;
  question: string;
  options: [string, string, string, string];
  answer: "A" | "B" | "C" | "D";
  explanation: string;
};

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  {
    id: "q01",
    question: "Who holds the MLB record for most career home runs?",
    options: ["Hank Aaron", "Barry Bonds", "Babe Ruth", "Alex Rodriguez"],
    answer: "B",
    explanation: "Barry Bonds hit 762 career home runs, surpassing Hank Aaron's record of 755.",
  },
  {
    id: "q02",
    question: "What year was the first modern World Series played?",
    options: ["1898", "1900", "1903", "1910"],
    answer: "C",
    explanation: "The first modern World Series was played in 1903 between the Boston Americans and Pittsburgh Pirates.",
  },
  {
    id: "q03",
    question: "How many stitches are on a regulation MLB baseball?",
    options: ["88", "96", "108", "120"],
    answer: "C",
    explanation: "A regulation MLB baseball has exactly 108 double stitches (216 individual stitches).",
  },
  {
    id: "q04",
    question: "Joe DiMaggio's consecutive-game hitting streak in 1941 stands at how many games?",
    options: ["44", "48", "52", "56"],
    answer: "D",
    explanation: "Joe DiMaggio hit safely in 56 consecutive games in 1941 — a record that still stands today.",
  },
  {
    id: "q05",
    question: "What is the distance from home plate to the pitcher's mound in MLB?",
    options: ["58.5 feet", "60.5 feet", "62 feet", "64 feet"],
    answer: "B",
    explanation: "The pitcher's mound is 60 feet 6 inches (60.5 ft) from home plate.",
  },
  {
    id: "q06",
    question: "Which franchise has won the most World Series championships?",
    options: ["Boston Red Sox", "St. Louis Cardinals", "Los Angeles Dodgers", "New York Yankees"],
    answer: "D",
    explanation: "The New York Yankees have won 27 World Series titles, far more than any other team.",
  },
  {
    id: "q07",
    question: "What is a 'golden sombrero' in baseball?",
    options: [
      "Hitting a walk-off home run",
      "Striking out four times in one game",
      "Hitting for the cycle",
      "A no-hitter through 6 innings",
    ],
    answer: "B",
    explanation: "A golden sombrero is when a batter strikes out four times in a single game.",
  },
  {
    id: "q08",
    question: "Who is known as 'The Say Hey Kid'?",
    options: ["Mickey Mantle", "Duke Snider", "Stan Musial", "Willie Mays"],
    answer: "D",
    explanation: "Willie Mays earned the nickname 'The Say Hey Kid' early in his career with the New York Giants.",
  },
  {
    id: "q09",
    question: "What does ERA stand for?",
    options: [
      "Extra Run Average",
      "Error Run Analysis",
      "Earned Run Average",
      "Extra Runs Allowed",
    ],
    answer: "C",
    explanation: "ERA stands for Earned Run Average — the average number of earned runs a pitcher allows per 9 innings.",
  },
  {
    id: "q10",
    question: "Who broke Major League Baseball's color barrier in 1947?",
    options: ["Satchel Paige", "Larry Doby", "Josh Gibson", "Jackie Robinson"],
    answer: "D",
    explanation: "Jackie Robinson broke MLB's color barrier on April 15, 1947, when he took the field for the Brooklyn Dodgers.",
  },
  {
    id: "q11",
    question: "What does WHIP stand for in baseball statistics?",
    options: [
      "Walks and Hits per Inning Pitched",
      "Walks, Hits, and Innings Pitched",
      "Wild pitches, Hits, Innings Pitched",
      "Weighted Hits In Pitching",
    ],
    answer: "A",
    explanation: "WHIP stands for Walks and Hits per Inning Pitched — a measure of how many base runners a pitcher allows per inning.",
  },
  {
    id: "q12",
    question: "Who holds the MLB record for most career stolen bases?",
    options: ["Lou Brock", "Tim Raines", "Vince Coleman", "Rickey Henderson"],
    answer: "D",
    explanation: "Rickey Henderson stole 1,406 bases in his career, nearly 500 more than second-place Lou Brock.",
  },
  {
    id: "q13",
    question: "What is an 'infield fly' in baseball?",
    options: [
      "Any fly ball hit to the infield",
      "A balk by the pitcher",
      "An automatic out on a pop-up with runners on 1st and 2nd (or bases loaded) and less than 2 outs",
      "A foul tip caught by the catcher",
    ],
    answer: "C",
    explanation: "The infield fly rule calls the batter automatically out to prevent fielders from intentionally dropping pop-ups to get easy double plays.",
  },
  {
    id: "q14",
    question: "What does OBP stand for?",
    options: [
      "Official Batter Points",
      "On-Base Percentage",
      "Out-Ball Percentage",
      "Overall Batting Performance",
    ],
    answer: "B",
    explanation: "OBP (On-Base Percentage) measures how often a batter reaches base via hit, walk, or hit-by-pitch.",
  },
  {
    id: "q15",
    question: "Nolan Ryan set the single-season strikeout record in 1973 with how many Ks?",
    options: ["348", "363", "383", "401"],
    answer: "C",
    explanation: "Nolan Ryan struck out 383 batters in 1973 with the California Angels, a record that still stands.",
  },
  {
    id: "q16",
    question: "What is a 'squeeze play'?",
    options: [
      "A pickoff attempt at first base",
      "A double steal with runners on 1st and 2nd",
      "A bunt designed to score a runner from third base",
      "A hit-and-run with a runner on second",
    ],
    answer: "C",
    explanation: "A squeeze play is when a batter bunts with a runner on third base, trying to score the runner on the play.",
  },
  {
    id: "q17",
    question: "What is 'painting the corner' in baseball?",
    options: [
      "A hit down the foul line",
      "A pitch that barely catches the edge of the strike zone",
      "A stolen base on a pitch in the dirt",
      "A slide into home plate",
    ],
    answer: "B",
    explanation: "Painting the corner means throwing a pitch that catches the very edge of the strike zone — a tough pitch for hitters to hit and umpires to call.",
  },
  {
    id: "q18",
    question: "In what year did the designated hitter rule first appear in the American League?",
    options: ["1968", "1971", "1973", "1976"],
    answer: "C",
    explanation: "The American League adopted the DH rule in 1973. The NL followed in 2022 when MLB made it universal.",
  },
  {
    id: "q19",
    question: "What does 'going yard' mean in baseball slang?",
    options: ["Stealing home plate", "Hitting a triple", "Hitting a home run", "An inside-the-park home run only"],
    answer: "C",
    explanation: "'Going yard' means hitting a home run — the ball leaves the park (the yard).",
  },
  {
    id: "q20",
    question: "A pitcher who records 27 consecutive outs without allowing a baserunner has thrown a…",
    options: ["One-hitter", "Perfect game", "No-hitter", "Complete game shutout"],
    answer: "B",
    explanation: "A perfect game requires retiring all 27 batters in order — no hits, no walks, no errors, no runners of any kind.",
  },
  {
    id: "q21",
    question: "What is a 'rundown' in baseball?",
    options: [
      "A play where the fielding team runs down a fly ball",
      "A play where a baserunner is caught between two bases and fielders tag them out",
      "A sprint time drill in practice",
      "When a pitcher's velocity drops late in the game",
    ],
    answer: "B",
    explanation: "A rundown (also called a 'pickle') is when a baserunner is caught between two bases and fielders throw back and forth trying to tag them out.",
  },
  {
    id: "q22",
    question: "How many balls does it take to walk a batter?",
    options: ["3", "4", "5", "It depends on the count"],
    answer: "B",
    explanation: "Four balls result in a walk (also called a base on balls), allowing the batter to advance to first base.",
  },
  {
    id: "q23",
    question: "Cal Ripken Jr. is famous for playing in how many consecutive games?",
    options: ["1,897", "2,130", "2,632", "2,900"],
    answer: "C",
    explanation: "Cal Ripken Jr. played in 2,632 consecutive games from 1982 to 1998, breaking Lou Gehrig's record of 2,130.",
  },
  {
    id: "q24",
    question: "What pitch typically moves away from a right-handed batter when thrown by a right-handed pitcher?",
    options: ["Two-seam fastball", "Curveball", "Changeup", "Slider"],
    answer: "D",
    explanation: "A slider thrown by a right-handed pitcher typically breaks down and away from a right-handed batter.",
  },
  {
    id: "q25",
    question: "What does it mean to 'hit for the cycle'?",
    options: [
      "Hit a home run in four consecutive at-bats",
      "Hit a single, double, triple, and home run in the same game",
      "Go 4-for-4 in a game",
      "Hit a leadoff home run four games in a row",
    ],
    answer: "B",
    explanation: "Hitting for the cycle means a batter gets a single, double, triple, and home run all in the same game — a rare feat.",
  },
  {
    id: "q26",
    question: "What is the standard height of a pitcher's mound in MLB?",
    options: ["8 inches", "10 inches", "12 inches", "15 inches"],
    answer: "B",
    explanation: "The pitcher's mound is 10 inches above the level of home plate. It was lowered from 15 inches after the 1968 'Year of the Pitcher.'",
  },
  {
    id: "q27",
    question: "Which player is nicknamed 'The Kid' and won the 1997 World Series MVP?",
    options: ["Ken Griffey Jr.", "Liván Hernández", "Derek Jeter", "Gary Sheffield"],
    answer: "B",
    explanation: "Liván Hernández won the 1997 World Series MVP with the Florida Marlins. Ken Griffey Jr. is 'The Kid' but never won a World Series.",
  },
  {
    id: "q28",
    question: "What is a 'can of corn' in baseball?",
    options: [
      "A slow roller to the infield",
      "An easy, routine fly ball to an outfielder",
      "A pitch tipped off the catcher's glove",
      "A double play ball",
    ],
    answer: "B",
    explanation: "A 'can of corn' is an easy fly ball to an outfielder — the term dates back to old grocery stores where clerks used a pole to knock canned goods off high shelves into their aprons.",
  },
  {
    id: "q29",
    question: "How many innings are in a regulation MLB game?",
    options: ["7", "8", "9", "It depends on the score"],
    answer: "C",
    explanation: "A regulation MLB game is 9 innings. A game can end earlier if it's official (5+ innings) and weather or other conditions prevent completion.",
  },
  {
    id: "q30",
    question: "Who won the most Cy Young Awards in MLB history?",
    options: ["Roger Clemens", "Randy Johnson", "Greg Maddux", "Clayton Kershaw"],
    answer: "A",
    explanation: "Roger Clemens won 7 Cy Young Awards — more than any other pitcher in history.",
  },
  {
    id: "q31",
    question: "What does 'OPS' stand for in batting statistics?",
    options: [
      "On-base Plus Slugging",
      "Overall Player Score",
      "Official Plate Statistics",
      "On-base Percentage Score",
    ],
    answer: "A",
    explanation: "OPS (On-base Plus Slugging) adds a player's on-base percentage and slugging percentage together and is a quick measure of offensive value.",
  },
  {
    id: "q32",
    question: "What is a 'walk-off' in baseball?",
    options: [
      "When a pitcher is pulled from the game",
      "When a batter takes four balls for a walk",
      "A hit or play that ends the game in the home team's favor in the last inning",
      "When a player is ejected and walks off the field",
    ],
    answer: "C",
    explanation: "A walk-off is any play that ends the game with the home team winning — the fielding team literally has to walk off the field.",
  },
  {
    id: "q33",
    question: "Which pitcher holds the MLB record for most career strikeouts?",
    options: ["Randy Johnson", "Roger Clemens", "Steve Carlton", "Nolan Ryan"],
    answer: "D",
    explanation: "Nolan Ryan struck out 5,714 batters in his career — over 800 more than second-place Randy Johnson (4,875).",
  },
  {
    id: "q34",
    question: "What is a 'rubber game' in baseball?",
    options: [
      "A game played on artificial turf",
      "The deciding third game of a three-game series",
      "An extra-innings game",
      "A rainout makeup game",
    ],
    answer: "B",
    explanation: "A rubber game is the deciding game of a series when each team has won an equal number of games — the team that wins 'breaks the rubber.'",
  },
  {
    id: "q35",
    question: "Ted Williams hit .406 in 1941. What does this mean?",
    options: [
      "He had 406 total hits",
      "He reached base 40.6% of the time",
      "He got a hit in 40.6% of his at-bats",
      "He had an OPS of .406",
    ],
    answer: "C",
    explanation: "A batting average of .406 means Williams got a hit in 40.6% of his official at-bats. No player has batted .400 or higher since.",
  },
  {
    id: "q36",
    question: "What is the 'hot corner' in baseball?",
    options: ["Home plate", "Third base", "The pitcher's mound", "First base"],
    answer: "B",
    explanation: "Third base is called the 'hot corner' because batters often pull hard line drives toward third basemen, requiring quick reflexes.",
  },
  {
    id: "q37",
    question: "Which team did Babe Ruth play for before the New York Yankees?",
    options: ["New York Giants", "Philadelphia Athletics", "Boston Red Sox", "Detroit Tigers"],
    answer: "C",
    explanation: "Babe Ruth started his career with the Boston Red Sox and was sold to the Yankees after the 1919 season — a trade that became known as the 'Curse of the Bambino.'",
  },
  {
    id: "q38",
    question: "What does 'BB' stand for on a baseball scorecard?",
    options: ["Bunt Balk", "Base on Balls", "Batter's Box", "Batted Ball"],
    answer: "B",
    explanation: "BB stands for Base on Balls — the official term for a walk, when a batter receives four balls and advances to first base.",
  },
  {
    id: "q39",
    question: "What is a 'sacrifice fly'?",
    options: [
      "A bunt that advances a runner",
      "A fly ball caught for an out that scores a runner from third",
      "A pop-up the catcher drops intentionally",
      "A fly ball that lands in foul territory",
    ],
    answer: "B",
    explanation: "A sacrifice fly is a fly ball caught for an out that allows a runner on third to tag up and score. It does not count against the batter's average.",
  },
  {
    id: "q40",
    question: "What year was the MLB draft introduced?",
    options: ["1955", "1960", "1965", "1970"],
    answer: "C",
    explanation: "The MLB First-Year Player Draft was introduced in 1965 to give weaker teams priority access to amateur talent.",
  },
  {
    id: "q41",
    question: "What is the distance between each base on a standard baseball diamond?",
    options: ["80 feet", "90 feet", "100 feet", "110 feet"],
    answer: "B",
    explanation: "The bases are 90 feet apart on a standard baseball diamond — a distance that creates extremely close plays at first base.",
  },
  {
    id: "q42",
    question: "Mike Trout won his first MVP award with which team?",
    options: ["Anaheim Angels", "Los Angeles Angels", "California Angels", "Texas Rangers"],
    answer: "B",
    explanation: "Mike Trout won the 2014 AL MVP (his first unanimous MVP) with the Los Angeles Angels of Anaheim.",
  },
  {
    id: "q43",
    question: "What is a 'utility player' in baseball?",
    options: [
      "A player who handles the team's equipment",
      "A backup catcher",
      "A player who can play multiple positions",
      "A player who only pinch-hits",
    ],
    answer: "C",
    explanation: "A utility player is versatile enough to play multiple positions, giving the manager flexibility with lineups and substitutions.",
  },
  {
    id: "q44",
    question: "Which stat measures the total bases a batter accumulates per at-bat?",
    options: ["Batting Average", "On-Base Percentage", "Slugging Percentage", "wRC+"],
    answer: "C",
    explanation: "Slugging percentage divides total bases (1 for single, 2 for double, 3 for triple, 4 for HR) by at-bats.",
  },
  {
    id: "q45",
    question: "What is a 'balk' in baseball?",
    options: [
      "A pitch that hits the batter",
      "An illegal pitching motion that allows baserunners to advance one base",
      "A pitch that bounces in the dirt",
      "When a fielder drops a throw",
    ],
    answer: "B",
    explanation: "A balk is an illegal motion by the pitcher with runners on base. All runners advance one base as a penalty.",
  },
  {
    id: "q46",
    question: "Mariano Rivera is famous for which pitch?",
    options: ["Knuckleball", "Eephus pitch", "Cut fastball (cutter)", "Split-finger fastball"],
    answer: "C",
    explanation: "Mariano Rivera's cut fastball (cutter) was arguably the most dominant single pitch in baseball history, helping him become the all-time saves leader.",
  },
  {
    id: "q47",
    question: "What does 'BABIP' stand for?",
    options: [
      "Batting Average on Balls In Play",
      "Bases Allowed By Innings Pitched",
      "Batted Average By Infield Position",
      "Batting Average Based on Individual Performance",
    ],
    answer: "A",
    explanation: "BABIP (Batting Average on Balls In Play) measures how often balls put in play fall for hits, excluding home runs and strikeouts. It helps evaluate whether results reflect true skill or luck.",
  },
  {
    id: "q48",
    question: "What is a 'no-doubter' home run?",
    options: [
      "A home run that barely clears the fence",
      "A home run so well-hit there is no doubt it will leave the park",
      "A home run in the 9th inning",
      "A walk-off home run",
    ],
    answer: "B",
    explanation: "A 'no-doubter' is a home run hit so hard and so far that there was never any question it was going out — usually a ball crushed to deep center or the upper deck.",
  },
  {
    id: "q49",
    question: "Who is the only pitcher to throw two no-hitters in the same season in the modern era?",
    options: ["Sandy Koufax", "Nolan Ryan", "Johnny Vander Meer", "Bob Feller"],
    answer: "C",
    explanation: "Johnny Vander Meer threw back-to-back no-hitters in June 1938 — the only pitcher ever to throw two consecutive no-hitters.",
  },
  {
    id: "q50",
    question: "What is the proper way for a fielder to back up a base on a throw?",
    options: [
      "Stand directly behind the base",
      "Stand at an angle behind the base so an overthrow doesn't get past you",
      "Stand in front of the base to cut the ball off",
      "Back up is not necessary if another fielder is covering",
    ],
    answer: "B",
    explanation: "A backup fielder should angle themselves behind the base so an overthrow or wild bounce doesn't get past them and allow extra bases.",
  },
  {
    id: "q51",
    question: "Which of the following is NOT one of the 13 ways a batter can legally reach first base?",
    options: [
      "Catcher's interference",
      "Dropped third strike",
      "Fair ball hits the first base umpire",
      "Fielder's choice",
    ],
    answer: "C",
    explanation: "A fair ball hitting an umpire is no longer a live-ball situation under modern rules — the ball is dead. The 13 ways include: single, double, triple, HR, walk, HBP, error, fielder's choice, dropped 3rd strike, catcher's interference, obstruction, fan interference, and fair ball hitting a runner.",
  },
  {
    id: "q52",
    question: "What is the 'shift' in modern baseball and why have teams moved away from it?",
    options: [
      "Moving all outfielders to one side; banned by MLB rule in 2023 requiring two infielders on each side of second base",
      "Moving the pitcher to a different arm angle mid-game; now illegal",
      "A defensive rotation where all fielders shift one position clockwise; rarely used",
      "Pulling the infield in with runners in scoring position; still widely used",
    ],
    answer: "A",
    explanation: "The extreme infield shift — stacking three or four infielders on one side against pull hitters — was banned starting in 2023. MLB now requires two infielders on each side of second base when the pitch is thrown.",
  },
  {
    id: "q53",
    question: "Sandy Koufax retired at age 30 due to injury. What was his career ERA, and why is it so remarkable?",
    options: [
      "2.76 — remarkable because he pitched during the high-offense 1950s",
      "2.36 — one of the lowest in the live-ball era, compiled across 12 seasons",
      "3.12 — remarkable because he had no fastball early in his career",
      "1.97 — the lowest career ERA of any starter with 2,000+ innings",
    ],
    answer: "B",
    explanation: "Sandy Koufax finished with a career ERA of 2.76 — but his peak ERA from 1962–1966 was even more staggering. He won three Cy Young Awards in four years and threw four no-hitters including a perfect game, all before arthritis in his elbow ended his career.",
  },
  {
    id: "q54",
    question: "In a double steal with runners on 1st and 3rd, what is the defense's primary decision point?",
    options: [
      "Whether to throw to second base or hold the ball and let both runners advance",
      "Whether to throw through to second and risk the runner scoring from third, or cut the throw and try to get the runner at third going home",
      "Whether to intentionally walk the batter to set up a force play",
      "Whether to call a pitchout and throw directly to third",
    ],
    answer: "B",
    explanation: "The 1st-and-3rd double steal puts the defense in a dilemma. Throwing through to second gives the runner on third a chance to score. The defense can cut the throw — to a middleman or the pitcher — and try to catch the runner breaking from third. The catcher and infield must communicate pre-pitch on what they'll do.",
  },
  {
    id: "q55",
    question: "What does 'WAR' stand for, and what does a WAR of 0 mean?",
    options: [
      "Wins Above Replacement; a player contributing 0 WAR is performing at a replacement-level (readily available) player's level",
      "Weighted At-bat Rating; 0 means the player has not come to bat yet",
      "Wins Against Roster; 0 means the player has contributed no wins to their team",
      "Win Adjustment Rating; 0 means the player breaks even on offense and defense",
    ],
    answer: "A",
    explanation: "WAR (Wins Above Replacement) measures how many more wins a player provides compared to a freely available replacement-level player. A WAR of 0 means you could swap in a minor league call-up and get the same production. A full-time starter typically needs 2+ WAR to justify roster spot; All-Star caliber is 5+; MVP level is 8+.",
  },
  {
    id: "q56",
    question: "What is the correct arm path for generating a strong, repeatable throw from the outfield?",
    options: [
      "Short arm action, sidearm release to keep the ball low on a line",
      "Long arm circle, high elbow above the shoulder at release, and follow through across the body",
      "Push the ball forward from the chest like a shot put for maximum momentum",
      "Release directly overhead with no follow-through to prevent injury",
    ],
    answer: "B",
    explanation: "A strong outfield throw uses a full arm circle to build momentum, elbow at or above shoulder height at release point, and a full follow-through across the body. Short-arming (cutting the arm circle short) loses velocity and accuracy. The crow hop before throwing transfers lower-body momentum into the throw.",
  },
  {
    id: "q57",
    question: "Roger Maris hit 61 home runs in 1961 to break Babe Ruth's single-season record. Why was the record initially controversial?",
    options: [
      "Maris was later found to have used a corked bat",
      "The 1961 season was 162 games while Ruth's record was set in a 154-game season, leading Commissioner Ford Frick to add an asterisk",
      "Maris played half his games at Yankee Stadium, which had a shorter right field fence",
      "Multiple players disputed the official scorer's ruling on several borderline home runs",
    ],
    answer: "B",
    explanation: "Commissioner Ford Frick — a close friend of Babe Ruth — ruled that Maris would need to break the record within the original 154-game schedule or the record would carry a separate notation. Though no literal asterisk appeared in the record books, the controversy stuck. MLB officially recognized Maris's 61 as the clean record in 1991.",
  },
  {
    id: "q58",
    question: "What is the difference between a 'cut fastball' and a 'two-seam fastball'?",
    options: [
      "They are the same pitch with different names depending on the pitcher's handedness",
      "A cutter breaks sharply late toward the pitcher's glove side; a two-seamer runs toward the arm side with more sinking action",
      "A cutter is slower and has more drop; a two-seamer is faster and breaks up in the zone",
      "A two-seamer is thrown only by left-handed pitchers; a cutter is a right-handed pitch",
    ],
    answer: "B",
    explanation: "A cutter (cut fastball) breaks hard and late toward the pitcher's glove side — think Mariano Rivera cutting into left-handed hitters' hands. A two-seamer runs in the opposite direction, moving toward the arm side with sinking action, generating weak ground ball contact. Both are fastball variants, but they move in opposite horizontal directions.",
  },
  {
    id: "q59",
    question: "What is 'launch angle' and what range is generally considered optimal for home runs?",
    options: [
      "The angle of the pitcher's arm at release; optimal is 90 degrees",
      "The vertical angle at which the ball leaves the bat; optimal home run range is roughly 25–35 degrees",
      "The angle of a baserunner's path rounding a base; optimal is 45 degrees",
      "The angle of the catcher's throw to second base; optimal is 10–15 degrees",
    ],
    answer: "B",
    explanation: "Launch angle is the vertical angle at which the ball leaves the bat. Research from the Statcast era shows that balls hit at 25–35 degrees with sufficient exit velocity are most likely to leave the park. Below 10 degrees tends to be ground balls; above 50 degrees is pop-ups. The 'fly ball revolution' of the 2010s came from hitters intentionally raising their launch angle.",
  },
  {
    id: "q60",
    question: "Who holds the record for most career saves in MLB history, and what is that number?",
    options: [
      "Mariano Rivera — 652",
      "Trevor Hoffman — 601",
      "Lee Smith — 478",
      "Billy Wagner — 422",
    ],
    answer: "A",
    explanation: "Mariano Rivera retired in 2013 with 652 career saves — the all-time record. Trevor Hoffman is second at 601. Rivera was also the first unanimous Hall of Fame inductee (2019), receiving a vote on every ballot.",
  },
  {
    id: "q61",
    question: "What does it mean when a pitcher 'pitches to contact' versus 'pitching to miss bats'?",
    options: [
      "Pitching to contact means deliberately hitting batters; pitching to miss bats means avoiding HBPs",
      "Pitching to contact means trusting the defense by inducing weak contact rather than chasing strikeouts; pitching to miss bats means prioritizing high-velocity, high-spin pitches to generate swings and misses",
      "Pitching to contact is a strategy for relievers only; pitching to miss bats is for starters only",
      "They refer to the same approach — both terms describe attacking the strike zone aggressively",
    ],
    answer: "B",
    explanation: "A 'pitch to contact' approach prioritizes efficiency and letting the defense make plays — good when you have a strong infield or want to save pitches deep into games. 'Missing bats' through high-strikeout stuff reduces dependence on the defense but costs more pitches. Elite starters often blend both depending on the count and situation.",
  },
  {
    id: "q62",
    question: "What is the 'hidden ball trick' and when is it legal?",
    options: [
      "A pitcher hiding the ball in their glove between innings; legal at any time",
      "A fielder pretending to throw to a base while keeping the ball, then tagging out a runner who leads off; legal as long as the pitcher is off the mound and not on the rubber",
      "A catcher faking a throw to second then throwing to third; legal only with a runner on third",
      "A pickoff move where the pitcher throws to a base without stepping off the rubber; illegal and ruled a balk",
    ],
    answer: "B",
    explanation: "The hidden ball trick is when a fielder conceals the ball and tags a runner who thinks the ball is back with the pitcher. It's legal as long as the pitcher is not standing on or astride the rubber — if they step on the rubber without the ball, it's a balk. It rarely works above youth levels but is perfectly legal.",
  },
  {
    id: "q63",
    question: "What was the '1994 Montreal Expos' situation, and why is it historically significant?",
    options: [
      "They won the World Series with the lowest payroll in MLB history",
      "They had the best record in baseball when the players' strike ended the season, denying them a likely World Series run; the team never recovered and relocated to Washington D.C. in 2005",
      "They became the first Canadian team to reach the World Series, losing in 7 games",
      "They set the record for most losses in a single season following a blockbuster trade",
    ],
    answer: "B",
    explanation: "The 1994 Expos (74–40, .649 winning percentage) were on pace to be one of the greatest teams ever when the August players' strike wiped out the rest of the season and the World Series. With a tiny market and no revenue from a potential postseason run, the franchise collapsed financially, lost key players, and eventually relocated to become the Washington Nationals in 2005.",
  },
  {
    id: "q64",
    question: "When a runner on first breaks for second on a hit-and-run, what is the batter's primary responsibility?",
    options: [
      "Hit the ball as hard as possible to any part of the field",
      "Swing at the pitch regardless of location to protect the runner and ideally hit behind the runner into the vacated right side of the infield",
      "Take the pitch and let the runner attempt to steal",
      "Bunt the ball toward third base to create a distraction",
    ],
    answer: "B",
    explanation: "On a hit-and-run, the batter must swing to protect the running. Even at a borderline pitch, a called strike or swing-and-miss leaves the runner exposed to being thrown out. Ideally the batter hits the ball to the right side (where the 2B has vacated to cover second) through the hole, advancing the runner to third.",
  },
  {
    id: "q65",
    question: "What is 'spin rate' and why does it matter for pitchers?",
    options: [
      "The speed at which the pitcher's arm rotates; higher spin rate means more velocity",
      "The rotations per minute (RPM) a pitched ball spins, which affects how much the pitch moves — higher spin on a fastball creates 'rise' and more swing-and-miss; on breaking balls it creates sharper bite",
      "The rate at which a pitcher alternates between pitch types during a game",
      "A measure of how quickly a catcher's glove rotates when framing pitches",
    ],
    answer: "B",
    explanation: "Spin rate (measured in RPM by Statcast) determines how much a pitch moves. A high-spin four-seam fastball appears to 'rise' (it drops less than expected) and generates more whiffs up in the zone. A high-spin curveball breaks sharper and later. The Statcast era revealed that spin rate is nearly as important as velocity for pitch effectiveness.",
  },
  {
    id: "q66",
    question: "What is the 'suicide squeeze' and how does it differ from a safety squeeze?",
    options: [
      "A suicide squeeze means the runner breaks for home on the pitch regardless of whether the batter makes contact; a safety squeeze means the runner only breaks if the batter lays down a successful bunt",
      "A suicide squeeze is when the batter bunts with two strikes; a safety squeeze is with fewer than two strikes",
      "They are the same play — 'suicide' and 'safety' just describe how hard the batter bunts the ball",
      "A suicide squeeze requires the runner to tag up at third; a safety squeeze allows the runner to lead off",
    ],
    answer: "A",
    explanation: "On the suicide squeeze, the runner breaks from third as soon as the pitcher starts the delivery — they're committed regardless of the pitch. This puts enormous pressure on the batter to make contact; a missed bunt or pop-up means an easy out at the plate. The safety squeeze lets the runner read the bunt first before committing, making it lower risk but less likely to score.",
  },
  {
    id: "q67",
    question: "Which of these best describes how to properly field a ground ball as an infielder?",
    options: [
      "Stand upright, let the ball come to you, and field it at waist height",
      "Charge when appropriate, get into a low athletic stance with the glove out front and low, field the ball in front of your body and slightly to the glove side, and funnel it to the throwing position",
      "Stay back on the ball so you have more time to react to bad hops, keeping your glove hand tucked close to your body",
      "Always field the ball on your backhand to get into throwing position faster",
    ],
    answer: "B",
    explanation: "Proper ground ball mechanics: charge under control, low stance, glove presented early and low (alligator hands — glove on bottom, bare hand on top ready to close), field slightly in front of and to the glove side of your body, and 'funnel' the ball up to your throwing slot in one smooth motion. Staying back gives bad hops more time to develop; attacking the ball on the way up is preferred.",
  },
  {
    id: "q68",
    question: "What is 'exit velocity' and what is considered elite at the MLB level?",
    options: [
      "The speed of the ball when it leaves the pitcher's hand; elite is 95+ mph",
      "The speed of the ball off the bat at contact; consistently above 95 mph exit velocity is considered above average, with elite hitters regularly hitting 105+ mph",
      "The speed of the runner leaving the batter's box; elite is under 4.0 seconds to first base",
      "The speed of the ball crossing home plate after a pitch; elite is above 100 mph",
    ],
    answer: "B",
    explanation: "Exit velocity (EV) measures how hard the ball comes off the bat. MLB average EV on contact is around 88–89 mph. Consistently hitting 95+ mph EV is above average; the elite tier (Mike Trout, Aaron Judge, Giancarlo Stanton) regularly reaches 110–115+ mph on well-struck balls. Higher exit velocity combined with optimal launch angle produces the most damage.",
  },
  {
    id: "q69",
    question: "Pete Rose holds the all-time MLB hits record with 4,256 career hits. Why is he not in the Hall of Fame?",
    options: [
      "He tested positive for performance-enhancing drugs in 1989",
      "He was permanently banned from baseball in 1989 for betting on baseball games, including games involving his own team",
      "He was convicted of tax evasion and served prison time, which disqualified him from the Hall",
      "He voluntarily retired before reaching the necessary milestones for Hall eligibility",
    ],
    answer: "B",
    explanation: "Pete Rose accepted a permanent ban from baseball in 1989 after an investigation found he had bet on games while managing the Cincinnati Reds. Because he is on baseball's ineligible list, he cannot be considered for the Hall of Fame. He admitted to betting on baseball in 2004. He passed away in 2024, still ineligible.",
  },
  {
    id: "q70",
    question: "What is a 'fungo' bat and what is it used for?",
    options: [
      "A weighted bat used for strength training in the on-deck circle",
      "A long, thin, lightweight bat used by coaches to hit fly balls and ground balls during fielding practice — not used in games",
      "A bat with a cupped end designed for power hitters to reduce weight at the barrel",
      "A bat made of aluminum used in batting practice only",
    ],
    answer: "B",
    explanation: "A fungo bat is longer and thinner than a regular bat, making it easier for coaches to toss a ball up and hit precise fly balls, ground balls, or line drives to specific fielders during practice. They're too fragile for actual hitting against live pitching and are strictly a practice tool.",
  },
  {
    id: "q71",
    question: "What is the significance of 'Moneyball' in baseball history?",
    options: [
      "It refers to the introduction of luxury tax payments for high-payroll teams in 1999",
      "It describes the 2002 Oakland A's approach under Billy Beane, using statistical analysis (sabermetrics) to find undervalued players and compete with a fraction of the big-market payrolls",
      "It was a salary arbitration case that set the precedent for modern player contracts",
      "It refers to the era of steroid-inflated offensive numbers that produced record salaries in the late 1990s",
    ],
    answer: "B",
    explanation: "The 2003 book (and 2011 film) 'Moneyball' documented how Billy Beane's Oakland A's used sabermetrics to identify undervalued metrics like on-base percentage, allowing them to compete despite one of baseball's lowest payrolls. It fundamentally changed how front offices evaluate players and is credited with launching the analytics revolution across all major sports.",
  },
  {
    id: "q72",
    question: "What does a pitcher mean when they say they're 'commanding' their fastball vs. simply 'throwing' it?",
    options: [
      "Commanding the fastball means hitting 95+ mph; throwing it means anything below that",
      "Commanding means the pitcher can locate the fastball to all four quadrants of the zone (in/out, up/down) and use it to set up other pitches; throwing it means just getting it over the plate",
      "Commanding a pitch means throwing it on a 3–2 count; throwing it is any other count",
      "There is no difference — pitching coaches use the terms interchangeably",
    ],
    answer: "B",
    explanation: "Pitch command is about precise location, not just velocity. A pitcher who 'commands' their fastball can dot the inner half for a lefty, climb the ladder up and in, or work the back-foot corner — using location to set up off-speed pitches and change eye levels. A pitcher who just 'throws' it is essentially pitching down the middle and relying on stuff alone.",
  },
  {
    id: "q73",
    question: "What is the 'battery' in baseball?",
    options: [
      "The group of relief pitchers in the bullpen",
      "The pitcher and catcher together, who form the core defensive unit",
      "The coaching staff responsible for game strategy",
      "The combination of a team's three best starting pitchers",
    ],
    answer: "B",
    explanation: "The 'battery' refers to the pitcher and catcher as a unit. The term dates back to the 19th century and draws from the military/electrical concept of paired units working together. A good battery relationship — where the catcher understands the pitcher's strengths and the pitcher trusts the catcher's pitch calling — is fundamental to pitching success.",
  },
  {
    id: "q74",
    question: "Why is it important for an outfielder to hit the cutoff man rather than always throwing directly to the plate?",
    options: [
      "It is never important — outfielders should always throw directly to the plate to save time",
      "Hitting the cutoff allows the relay man to redirect the throw if a different base becomes the better play, keeps the ball on line, and prevents a wild throw from allowing additional bases",
      "The cutoff rule is only used when the outfielder has a weak arm",
      "Hitting the cutoff is only required by rule on balls hit to left field",
    ],
    answer: "B",
    explanation: "The cutoff man serves multiple purposes: the relay throw can be redirected to a different base if the situation changes (e.g., a runner tries to advance to third while the play is at the plate), it keeps the ball on an accurate line to the target, and it prevents a wild throw from rolling to the backstop. A strong, accurate throw directly to the plate is preferred when the outfielder is close enough — but the cutoff is critical on deeper balls.",
  },
  {
    id: "q75",
    question: "What is 'pitch tunneling' and why is it effective?",
    options: [
      "Throwing all pitches directly over the middle of the plate to overpower hitters",
      "Designing pitch sequences so that different pitches (fastball, breaking ball, changeup) appear identical out of the hand and through the same 'tunnel' until they diverge near the plate — making it nearly impossible for hitters to distinguish pitch type early",
      "A pitching drill where pitchers aim at targets placed in the corners of the strike zone",
      "The mechanical path the pitching arm follows from the windup through the release point",
    ],
    answer: "B",
    explanation: "Pitch tunneling exploits the limits of hitter reaction time. Hitters must commit to their swing decision before the ball is halfway to the plate. If a fastball and curveball look identical for the first 20–30 feet out of the pitcher's hand, the hitter cannot tell them apart until it's too late to adjust. Elite pitchers design their arsenals so pitches share the same early path and only diverge near the batter.",
  },
];

export function getRandomQuestion(excludeIds: string[] = []): TriviaQuestion {
  const pool = TRIVIA_QUESTIONS.filter((q) => !excludeIds.includes(q.id));
  const source = pool.length > 0 ? pool : TRIVIA_QUESTIONS;
  return source[Math.floor(Math.random() * source.length)];
}
